#!/bin/bash


BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [ $BRANCH_NAME = "develop" ]; then
    TO_MERGE=$(grep -Go "\[.*\/.*\]" -m 1 $1)
    TO_MERGE=${TO_MERGE:1:-1}
    sed -i.bak -e "1cMerge \"$TO_MERGE\" into develop" $1
    exit
fi


if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop integration test extended)
fi


BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "\[$BRANCH_NAME\]" $1)

if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
  sed -i.bak -e "1s#^#$BRANCH_NAME: #" $1
fi
